# Generated by Django 5.2.16 on 2026-07-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='offered', max_length=20)),
                ('status_history', models.JSONField(default=list)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='loads.load')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.truck')),
            ],
        ),
    ]
