# Generated by Django 5.2.16 on 2026-07-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('fleet', '0002_driver_hos_violations_90d_and_more'),
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['offered', 'accepted', 'dispatched'])), fields=('load',), name='uniq_active_assignment_per_load'),
        ),
    ]
