# Generated by Django 5.2.16 on 2026-07-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.FloatField()),
                ('origin_lon', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lon', models.FloatField()),
                ('dest_market', models.CharField(max_length=40)),
                ('miles', models.FloatField()),
                ('rate_usd', models.FloatField()),
                ('equipment_type', models.CharField(choices=[('dry_van', 'Dry Van'), ('reefer', 'Reefer'), ('flatbed', 'Flatbed')], max_length=40)),
                ('pickup_window_start', models.DateTimeField()),
                ('pickup_window_end', models.DateTimeField()),
                ('est_transit_hours', models.FloatField()),
            ],
        ),
    ]
