# Generated by Django 5.2.16 on 2026-07-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diesel_usd_per_gal', models.FloatField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_runs', to='fleet.truck')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_mile_score', models.FloatField()),
                ('deadhead_penalty', models.FloatField()),
                ('fuel_efficiency_score', models.FloatField()),
                ('hos_feasibility', models.FloatField()),
                ('market_preference_score', models.FloatField()),
                ('overall', models.FloatField()),
                ('deadhead_miles', models.FloatField(default=0)),
                ('rate_per_mile', models.FloatField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('explanation_text', models.TextField(blank=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.load')),
                ('score_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scoring.scorerun')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
