# Generated by Django 5.2.16 on 2026-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaneRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_market', models.CharField(db_index=True, max_length=40)),
                ('week_start', models.DateField()),
                ('avg_rate_per_mile', models.FloatField()),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('dest_market', 'week_start')},
            },
        ),
    ]
