# Generated by Django 5.2.16 on 2026-07-12 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('dry_van', 'Dry Van'), ('reefer', 'Reefer'), ('flatbed', 'Flatbed')], max_length=40)),
                ('current_lat', models.FloatField()),
                ('current_lon', models.FloatField()),
                ('mpg', models.FloatField(default=6.5)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='fleet.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos_hours_remaining', models.FloatField()),
                ('home_base_lat', models.FloatField()),
                ('home_base_lon', models.FloatField()),
                ('preferred_markets', models.JSONField(default=list)),
                ('no_go_markets', models.JSONField(default=list)),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='fleet.truck')),
            ],
        ),
    ]
