# Generated by Django 5.2.16 on 2026-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='hos_violations_90d',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='inspection_pass_rate',
            field=models.FloatField(default=0.95),
        ),
        migrations.AddField(
            model_name='driver',
            name='on_time_pct',
            field=models.FloatField(default=0.9),
        ),
    ]
