# Generated by Django 5.2.16 on 2026-07-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_score', models.FloatField()),
                ('total_deadhead_miles', models.FloatField()),
                ('total_hours', models.FloatField(default=0)),
                ('total_rate_usd', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains_out', to='loads.load')),
                ('return_load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains_return', to='loads.load')),
            ],
        ),
    ]
